#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Pauldro\Minicli\v2\App\App;
use Minicli\Exception\CommandNotFoundException;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$app = new App([
    'theme' => 'Pauldro\\Minicli\\v2\\Output\\Theme\\Cli',
    'app_path' => [
         __DIR__ . '/app/Cmd/',
    ],
    'php_ini' => [
        'dir' => __DIR__ . '/php.d/',
        'files' => [
            'php-cli.ini'
        ]
    ]
]);

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->error("An error occurred:");
        $app->error($exception->getMessage());
    }
    return 1;
}

return 0;
